version: "2"
networks:
  mynet:
services:    
  db:
    image: classroom.example.com:5000/postgres
    container_name: "db"
    environment:
      POSTGRES_USER: ticketmonster
      POSTGRES_PASSWORD: ticketmonster-docker
    networks:
          - mynet
  mywildfly:
    image: classroom.example.com:5000/wildfly-ticketmonster
    networks:
          - mynet
    ports:
      - 8080
